#cloud-config
hostname: cloud-init-host1

packages:
  - ansible

runcmd:
  - ansible-pull -U https://github.com/bryopsida/ansible-pull-cloud-init -i $(hostname)/inventory.ini $(hostname)/playbook.yml
